### ISSUE TITLE
大佬～能不能推荐一下你的学习路线？

### ISSUE THREAD

**Issue by junqinyang** [liangyihuai/my_tensorflow#2]
最近在学习神经网络，苦于代码不会上手，想了解一下大佬的学习路线，有哪些资料？万分感谢～

**Comment by liangyihuai** [comment]
非常推荐吴恩达老师在coursera上面的《深度学习课程》，有五门课在里面，视频是免费的，不清楚现在的在线编程部分是否免费！

**Comment by liangyihuai** [comment]
> 最近在学习神经网络，苦于代码不会上手，想了解一下大佬的学习路线，有哪些资料？万分感谢～

非常推荐吴恩达老师在coursera上面的《深度学习课程》，把编程部分代码也做了。有五门课在里面，视频是免费的，不清楚现在的在线编程部分是否免费！

**Comment by junqinyang** [comment]
> > 最近在学习神经网络，苦于代码不会上手，想了解一下大佬的学习路线，有哪些资料？万分感谢～
> 
> 非常推荐吴恩达老师在coursera上面的《深度学习课程》，把编程部分代码也做了。有五门课在里面，视频是免费的，不清楚现在的在线编程部分是否免费！

好的！多谢大佬～

**Comment by junqinyang** [comment]
> > 最近在学习神经网络，苦于代码不会上手，想了解一下大佬的学习路线，有哪些资料？万分感谢～
> 
> 非常推荐吴恩达老师在coursera上面的《深度学习课程》，把编程部分代码也做了。有五门课在里面，视频是免费的，不清楚现在的在线编程部分是否免费！

大佬您好，我看了您在csdn上的resent代码分类手势识别的博客，能不能给个关于那个手势识别数据集的介绍链接呀？十分感谢～

**Comment by liangyihuai** [comment]
> > > 最近在学习神经网络，苦于代码不会上手，想了解一下大佬的学习路线，有哪些资料？万分感谢～
> > 
> > 
> > 非常推荐吴恩达老师在coursera上面的《深度学习课程》，把编程部分代码也做了。有五门课在里面，视频是免费的，不清楚现在的在线编程部分是否免费！
> 
> 大佬您好，我看了您在csdn上的resent代码分类手势识别的博客，能不能给个关于那个手势识别数据集的介绍链接呀？十分感谢～

这个就是在吴恩达深度学习课程中的数据，课程中有具体的介绍，只是课程中的代码不是使用tensorflow写的。不过代码部分你可以参考我的，相差不大

**Comment by liangyihuai** [comment]
> > > 最近在学习神经网络，苦于代码不会上手，想了解一下大佬的学习路线，有哪些资料？万分感谢～
> > 
> > 
> > 非常推荐吴恩达老师在coursera上面的《深度学习课程》，把编程部分代码也做了。有五门课在里面，视频是免费的，不清楚现在的在线编程部分是否免费！
> 
> 大佬您好，我看了您在csdn上的resent代码分类手势识别的博客，能不能给个关于那个手势识别数据集的介绍链接呀？十分感谢～

我不是大佬！！！！\\苦笑

**Comment by junqinyang** [comment]
> > > > 最近在学习神经网络，苦于代码不会上手，想了解一下大佬的学习路线，有哪些资料？万分感谢～
> > > 
> > > 
> > > 非常推荐吴恩达老师在coursera上面的《深度学习课程》，把编程部分代码也做了。有五门课在里面，视频是免费的，不清楚现在的在线编程部分是否免费！
> > 
> > 
> > 大佬您好，我看了您在csdn上的resent代码分类手势识别的博客，能不能给个关于那个手势识别数据集的介绍链接呀？十分感谢～
> 
> 我不是大佬！！！！\苦笑

哈哈哈 好的！谢谢～
