### ISSUE TITLE
残差网络为啥结果时好时坏

### ISSUE THREAD

**Issue by zhaobeile** [liangyihuai/my_tensorflow#3]
大佬，我跑您的残差网络，手势分类，为啥结果时好时坏。还有大佬不加偏置的原因是啥

**Comment by liangyihuai** [comment]
第一个问题，效果不稳定的原因是每次训练前参数是随机生成的，使用反向传播和梯度下降，导致有时候只收敛到局部最优。使用adam和滑动平均试试。


问题二，该模型使用了batch normalization，对每一层网络的输出数据进行了标准化。你查一下batch normalization就明白了。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: zhaobeile <notifications@github.com>
发送时间: 2019年7月23日 10:47
收件人: liangyihuai/my_tensorflow <my_tensorflow@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[liangyihuai/my_tensorflow] 残差网络为啥结果时好时坏 (#3)




大佬，我跑您的残差网络，手势分类，为啥结果时好时坏。还有大佬不加偏置的原因是啥

**Comment by zhaobeile** [comment]
另外还有一个问题，您的代码结果过拟合为何如此严重，有改进版本吗

**Comment by liangyihuai** [comment]
该代码只是演示残差网络用的。




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: zhaobeile <notifications@github.com>
发送时间: 2019年7月23日 13:27
收件人: liangyihuai/my_tensorflow <my_tensorflow@noreply.github.com>
抄送: 蜗牛爱上星星 <1757153156@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[liangyihuai/my_tensorflow] 残差网络为啥结果时好时坏 (#3)




另外还有一个问题，您的代码结果过拟合为何如此严重，有改进版本吗
